let state, tab = 'overview', busy = false;
let actor = localStorage.getItem('skilldemo-actor') || 'alice';
let session = localStorage.getItem(`skilldemo-session-${actor}`) || `${actor}-${crypto.randomUUID().slice(0,8)}`;
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const titles = {overview:'让经验成为可复用能力',chat:'从真实任务开始',traces:'看清任务怎样形成',candidates:'只沉淀值得复用的经验',skills:'可复用、可追溯、可演化',review:'组织共享，从审核开始',runs:'保留证据，准备后续评估'};
const badge = (v, cls='') => `<span class="badge ${cls}">${esc(v)}</span>`;
const button = (label, action, id='', cls='') => `<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const empty = text => `<div class="empty">${text}</div>`;
function artifactLinks(runId, result) {
 const files=[...(result?.artifacts||[]),...(result?.package?[result.package]:[])];
 return files.map(f=>`<a href="/api/artifact?actor=${encodeURIComponent(actor)}&run=${encodeURIComponent(runId)}&path=${encodeURIComponent(f.path)}" download="${esc(f.path.split(/[\\/]/).pop())}">${esc(f.path)}</a>`).join(' · ');
}
function turnText(t) {
 if(t.assistant?.trim()==='NO_REPLY')return t.artifacts?.length?'Agent 未附文字说明；已登记下方交付文件，请下载查看。':'Agent 本次未提供文字回复。';
 return t.assistant||t.error||'执行中…';
}
function detail(title, value) {$('detail-title').textContent=title;$('detail-body').textContent=typeof value==='string'?value:JSON.stringify(value,null,2);$('detail').showModal();}
function frontPanel(){return `<div class="panel"><div class="row spread"><h2>前三阶段 · 原事件到任务轨迹</h2>${button('处理前三阶段','stages')}</div><p class="muted">阶段1不调用模型；阶段2与3分别批量抽取、核验。未知业务结果保留。新版轨迹经阶段4提取方法并聚合为workflow；NEW候选交阶段5封装。</p><table><thead><tr><th>会话</th><th>1 · 问答整理</th><th>2 · 任务标注</th><th>3 · 轨迹恢复</th><th>证据</th></tr></thead><tbody>${(state.stageStatus||[]).map(s=>`<tr><td>${esc(s.session)}<br>${esc(s.purposeSplit)}</td><td>${esc(s.stage1)}</td><td>${esc(s.stage2)}</td><td>${esc(s.stage3)}<br>${esc(s.error||'')}</td><td>${button('查看阶段状态','stage-detail',s.id)}</td></tr>`).join('')}</tbody></table><details><summary>问答对象 / ${(state.pairs||[]).length} 个</summary>${(state.pairs||[]).map(p=>`<p>${badge(p.contentStatus)} ${esc(p.sourceUserMessageId)} · ${p.assistantSegments.length} 条助手消息 ${button('原问答与来源','pair-detail',p.id)}</p>`).join('')}</details><details><summary>逐对任务标注（含历史） / ${(state.pairAnnotations||[]).length} 个</summary>${(state.pairAnnotations||[]).map(a=>`<p>${esc(a.pairId)} · ${a.fragments.length} 个目标片段 ${button('候选与引用','annotation-detail',a.id)}</p>`).join('')}</details></div>`;}
async function api(path, body) {
 const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify({actor,...body}):undefined});
 const result=await response.json(); if(!response.ok)throw new Error(result.error||response.statusText);return result;
}
async function refresh(renderNow=true){state=await api('state?actor='+encodeURIComponent(actor));$('mode').textContent=state.mode==='replay'?'合成回放':'OpenClaw · 真实模式'; if(renderNow)render();}
function render(){
 $('title').textContent=titles[tab];$('actor').value=actor;
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
  $('notice').textContent=state.mode==='replay'?'当前是合成回放模式：回答与技能来自固定夹具，不代表真实模型能力。':state.runtime?.configured?`真实模型：${state.runtime.model}。选用技能会读取对应版本文件；读取回执、产物与usage见运行记录。`:'真实模式尚未配置模型。请在demo/.env填写DEMO_MODEL、DEMO_BASE_URL、DEMO_API_KEY后重启；不会回退到合成回答。';
 $('content').innerHTML=(tab==='traces'?frontPanel():'')+views[tab]();
 if(tab==='chat'){$('session').value=session;$('session-picker').value=state.turns.some(t=>t.session===session)?session:'';$('messages').scrollTop=$('messages').scrollHeight;}
}
const views={
overview(){const m=state.metrics;return `<div class="panel hero"><span class="eyebrow">CONVERSATION → EXPERIENCE → SKILL</span><h2>把修订过程留下，把重复生成减少。</h2><p>这里观察的是完整任务，而不只是一个问答对。新版前三阶段先保留原消息、整理问答，再由模型标注候选任务并恢复要求、反馈和尝试。新版轨迹进入workflow聚合与skill-creator封装；候选须由成员选择采纳，随后可在使用工作台选用。</p><div class="row">${button('开始任务会话','chat','','primary')}${state.mode==='replay'?button('加载完整回放示例','scenario'):button('检查 OpenClaw 配置','health')}${button('导出当前研究记录','export')}</div></div><div class="stats">${[['任务实例',state.traces.length,'多次改稿仍可属于一个任务'],['待审候选',state.candidates.filter(c=>c.status==='READY').length,'技术完成不等于业务成功'],['可用技能',state.skills.length,'个人库 + 已审核组织库'],['学习总派发',m.learning_plane_calls??m.learning_calls,'缺失 tokens 不记为 0']].map(x=>`<div class="stat"><label>${x[0]}</label><strong>${x[1]}</strong><small class="muted">${x[2]}</small></div>`).join('')}</div><div class="panel"><div class="row spread"><h2>完整算法链路</h2>${badge('阶段1 · 0 LLM；阶段2/3 · 语义抽取')}</div><div class="flow">${[['01 / 会话采集','原事件 → 问答对','保留原消息与配对依据'],['02 / 任务识别','逐对候选标注','完整问答 / 多目标分片 / RETURN'],['03 / 轨迹恢复','核验并组装轨迹','要求版本 / 尝试 / 反馈 / 未知'],['04–05 / 方法聚合与生成','workflow → 技能','受控聚类、独立creator封装'],['06–12 / 企业闭环','采纳与演化','旧版回放可体验；组织复用需审核']].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b>${x[2]}</div>`).join('')}</div><div class="row">${button(state.settings.autoLearn?'暂停自动学习':'启用自动学习','auto')}${button('运行一次学习周期','cycle')}<span class="muted">稳定期自动封口，无需用户点击“完成”。</span></div></div>`;},
chat(){const turns=state.turns.filter(t=>t.session===session);const chosen=(turns.at(-1)?.skills||[]).map(s=>s.id);return `<div class="two"><div class="panel"><div class="row spread"><h2>任务会话</h2>${button('新建会话','new-session')}</div><label class="muted">当前会话</label><input id="session" aria-label="会话ID"><select id="session-picker" aria-label="已有会话"><option value="">查看已有会话…</option>${[...new Set(state.turns.map(t=>t.session))].map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select><div id="messages" class="messages">${turns.map(t=>`<div class="bubble user"><small>用户</small>${esc(t.user)}</div><div class="bubble"><small>${esc(t.mode)} · ${esc(t.status)}</small>${esc(turnText(t))}<div>${artifactLinks(t.runId,t)}</div></div>`).join('')||empty('输入具体任务开始。<br>比如：整理销售周报，必须先扣除退款再汇总收入。')}</div><form id="chat-form"><div class="skill-select">${state.skills.map(s=>`<label><input type="checkbox" name="skills" value="${esc(s.id)}" ${chosen.includes(s.id)?'checked':''}> ${esc(s.title)} · v${s.version}</label>`).join('')}</div><textarea id="message" placeholder="描述任务，后续直接在对话中补充或纠错…" required></textarea><div class="row spread"><small class="muted">任务与反馈由后台语义抽取，不需要额外会话标记操作。</small><button class="primary" type="submit">发送给 ${state.mode==='openclaw'?'OpenClaw':'合成回放'}</button></div></form></div><div><div class="panel"><h3>Agent 能力</h3><p>真实模式提供模型调用、Python 脚本执行和官方 skill-creator。提炼阶段自动封装技能；也可输入 /skill-creator 加具体需求。交付文件会显示下载链接。</p><h3>怎样触发演化</h3><p>先在技能库采纳候选，再勾选 skill 完成一个新任务。若后续发现问题，直接说“不对，必须……”。后台会保留前一次使用记录，并判断是否形成 UPDATE。</p><p class="muted">“新任务：……”会建立独立目标。没有新的方法信息时，保留 SUPPORT，不强行改版。</p></div><div class="panel"><h3>导入已有会话</h3><p class="muted">原事件 JSONL：id、sessionId、role、content、sourceOrder、status，最多1000条；也接受旧问答格式（最多100条）。原事件历史会话只读，实际执行请新建会话。</p><input type="file" id="import-file" accept=".jsonl,.ndjson,.json"><p class="muted">不接受手填的“技能已使用”标签冒充实际版本回执。</p></div></div></div>`;},
traces(){return `<div class="panel"><div class="row spread"><h2>任务轨迹 / ${state.traces.length}</h2>${button('运行一次学习周期','cycle')}</div><p class="muted">封口只是稳定经验可进入提炼；未知结果仍显示 UNKNOWN。明确纠正可重新打开任务。</p></div><div class="panel"><h3>轨迹聚类 / ${(state.pools||[]).length} 个学习池</h3><p class="muted">新版轨迹先按共同处理流程聚类，再合并互补方法与条件分支；旧版回放保留原词法基线。单例可处理。</p>${(state.pools||[]).map(p=>`<p>${badge(p.state)} ${esc(p.id)} · ${p.members.length} 条独立任务 ${button('查看聚类依据','pool-detail',p.id)}</p>`).join('')||'<p class="muted">稳定的任务进入发现流程后在这里显示。</p>'}</div><div class="panel"><h3>阶段4 workflow / ${(state.workflows||[]).length}</h3>${(state.workflows||[]).map(w=>`<p>${badge(w.action)} ${badge(w.status)} ${esc(w.workflow.title)} · ${w.sourceRefs.length} 条来源 ${button('查看方法台账与条件','workflow-detail',w.id)}</p>`).join('')||'<p class="muted">暂无冻结workflow。</p>'}</div><div class="cards">${state.traces.map(t=>`<div class="card"><div class="row">${badge(t.state)}${badge(t.verification,'muted')}${badge('r'+t.revision,'muted')}${t.decision?badge(t.decision.action,t.decision.action==='DEFER'?'warn':''):''}</div><h3>${esc(t.goal)}</h3><p class="muted">${t.turns.length} 个运行片段 · ${esc(t.decision?.reason||(t.schemaVersion==='task-trace-v2'?'恢复完成，等待阶段4方法分析':'等待稳定期或更多证据'))}</p>${t.turns.map(x=>`<p><b>${esc(x.intent)}</b>　${esc(x.user)}<br><span class="muted">${esc(x.status)} · ${x.skills.map(s=>esc(s.id)+' v'+s.version).join(', ')||'未选技能'}</span></p>`).join('')}${button('查看完整证据与历史','trace-detail',t.id)}</div>`).join('')||empty('还没有明确任务。先在会话中提出一个具体目标。')}</div><div class="panel"><h3>未关联 / 噪声片段</h3>${state.turns.filter(t=>!t.taskId).map(t=>`<p>${badge(t.association,'muted')} ${esc(t.user)}</p>`).join('')||'<p class="muted">暂无</p>'}</div>`;},
candidates(){return `<div class="panel"><div class="row spread"><h2>技能候选 / ${state.candidates.length}</h2>${button('发现并生成','cycle')}</div><p class="muted">先冻结证据，再生成草稿。UPDATE在采纳前不改原版本，组织共享必须审核。</p></div><div class="cards">${state.candidates.map(c=>`<div class="card"><div class="row">${badge(c.action)}${badge(c.status,c.status==='FAILED'?'warn':'muted')}${badge(c.mode,'muted')}</div><h3>${esc(c.title)}</h3><p class="muted">${esc(c.target?'更新目标：'+c.target+' / v'+c.baseVersion:c.reason)}</p>${c.error?`<p>${esc(c.error)}</p>`:''}<div class="row">${button('查看草稿与来源','candidate-detail',c.id)}${c.status==='QUEUED'?button('生成','generate',c.id):''}${['READY','SUBMITTED'].includes(c.status)&&!c.installedSkill?button('纳入个人库','accept',c.id,'primary'):''}${['READY','INSTALLED'].includes(c.status)&&!c.submissionId?button('提交组织审核','submit',c.id):''}${['QUEUED','READY','FAILED'].includes(c.status)?button('拒绝候选','reject',c.id,'danger'):''}</div></div>`).join('')||empty('证据与workflow通过校验后，候选会出现在这里。')}</div>`;},
skills(){return `<div class="panel"><h2>技能库与版本</h2><p class="muted">技能包采用 SKILL.md 与可选资源目录。回滚创建一个新版本，历史不会被删除。</p></div><div class="cards">${state.skills.map(s=>`<div class="card"><div class="row">${badge(s.owner.startsWith('org:')?'已审核组织技能':'个人技能')}${badge('v'+s.version,'muted')}</div><h3>${esc(s.title)}</h3><p class="muted">${esc(s.id)} · ${s.files.length} 个文件 · hash ${esc(s.hash.slice(0,12))}</p><div class="row">${button('查看技能包','skill-detail',s.id)}<a href="/api/skill-package?actor=${encodeURIComponent(actor)}&id=${encodeURIComponent(s.id)}" download="${esc(s.id)}.skill">下载 .skill 包</a>${button('选用并开始任务','use-skill',s.id,'primary')}${button('版本历史','versions',s.id)}</div></div>`).join('')||empty('采纳候选后，即可在这里选用。')}</div>`;},
review(){return `<div class="panel"><h2>组织技能提审</h2><p class="muted">${actor==='reviewer'?'当前为演示审核员角色，可审核本组织提案。':'成员只能提交和查看自己的提案；切换到演示审核员可体验审批。'} 原始会话不随提案共享。</p></div><div class="cards">${state.submissions.map(s=>`<div class="card">${badge(s.status)}<h3>${esc(s.title)}</h3><p class="muted">提交者 ${esc(s.owner)} · 冻结包 ${esc(s.hash.slice(0,12))}</p><div class="row">${button('查看提审包','submission-detail',s.id)}${actor==='reviewer'&&s.status==='PENDING'?button('审核通过','approve',s.id,'primary')+button('驳回','deny',s.id,'danger'):''}</div></div>`).join('')||empty('暂无可见提案。')}</div>`;},
runs(){const m=state.metrics;return `<div class="stats">${[['执行派发',m.execution_calls],['学习总派发',m.learning_plane_calls??m.learning_calls],['已报告 tokens',m.reported_tokens??'未知'],['未知 usage',m.usage_missing_runs]].map(x=>`<div class="stat"><label>${x[0]}</label><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel"><div class="row spread"><h2>运行记录</h2>${button('导出 JSONL','export')}${button('检查真实运行时','health')}</div><p class="muted">失败派发计入成本记录。外层派发次数不等于内部模型调用次数，缺失计量保持未知。</p><table><thead><tr><th>用途</th><th>模式</th><th>状态</th><th>时间</th><th>证据</th></tr></thead><tbody>${state.runs.map(r=>`<tr><td>${esc(({learn:'提炼技能',detect:'旧版任务识别',detect_pairs:'阶段2 · 逐对任务标注',recover_trace:'阶段3 · 轨迹恢复',workflow_extract:'阶段4 · 方法抽取',workflow_merge:'阶段4 · workflow合并',workflow_creator:'阶段5 · 技能封装',chat:'执行任务'})[r.purpose]||r.purpose)}</td><td>${esc(r.mode)}</td><td>${esc(r.status)}</td><td>${new Date(r.started*1000).toLocaleTimeString()}</td><td>${button('查看','run-detail',r.id)}<div>${artifactLinks(r.id,r.result)}</div></td></tr>`).join('')}</tbody></table></div>`;}
};
async function action(name,id){
 if(busy)return;
 if(name==='chat'){tab='chat';render();return;}
 if(name==='new-session'){session=`${actor}-${crypto.randomUUID().slice(0,8)}`;localStorage.setItem(`skilldemo-session-${actor}`,session);render();return;}
 if(name==='export'){window.open('/api/export?actor='+encodeURIComponent(actor),'_blank');return;}
 const lookups={'stage-detail':'stageStatus','pair-detail':'pairs','annotation-detail':'pairAnnotations','pool-detail':'pools','trace-detail':'traces','workflow-detail':'workflows','candidate-detail':'candidates','skill-detail':'skills','submission-detail':'submissions','run-detail':'runs'};
 if(lookups[name]){const item=state[lookups[name]].find(x=>x.id===id);detail(titles[tab],item);return;}
 if(name==='versions'){
  const s=state.skills.find(x=>x.id===id); detail('版本历史',s.versions);
  const v=prompt('如需回滚，填写目标版本号；取消则只查看历史。');
  if(v!==null&&v.trim())await perform('rollback',{id,version:Number(v)});return;
 }
 if(name==='use-skill'){tab='chat';session=`${actor}-${crypto.randomUUID().slice(0,8)}`;render();document.querySelectorAll('input[name=skills]').forEach(x=>x.checked=x.value===id);$('message').focus();return;}
 if(name==='health'){detail('OpenClaw运行时',await api('health'));return;}
 if(name==='auto'){await perform('settings',{autoLearn:!state.settings.autoLearn});return;}
 await perform(name==='approve'||name==='deny'?'review':name,{id,approve:name==='approve'});
}
async function perform(path,body){busy=true;document.querySelectorAll('button').forEach(x=>x.disabled=true);$('notice').textContent='正在处理，运行证据会保留，请勿重复派发…';try{const r=await api(path,body);if(r.session)session=r.session;await refresh();if(r.error)$('notice').textContent=r.error;}catch(e){$('notice').textContent=e.message;}finally{busy=false;document.querySelectorAll('button').forEach(x=>x.disabled=false);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();}else if(b.dataset.action)action(b.dataset.action,b.dataset.id).catch(e=>$('notice').textContent=e.message);});
$('actor').addEventListener('change',async e=>{actor=e.target.value;localStorage.setItem('skilldemo-actor',actor);session=localStorage.getItem(`skilldemo-session-${actor}`)||`${actor}-${crypto.randomUUID().slice(0,8)}`;await refresh();});
$('close-detail').onclick=()=>$('detail').close();
document.addEventListener('change',e=>{if(e.target.id==='session-picker'&&e.target.value){session=e.target.value;localStorage.setItem(`skilldemo-session-${actor}`,session);render();}});
document.addEventListener('submit',async e=>{if(e.target.id!=='chat-form')return;e.preventDefault();session=$('session').value;localStorage.setItem(`skilldemo-session-${actor}`,session);await perform('chat',{session,message:$('message').value,skills:[...document.querySelectorAll('input[name=skills]:checked')].map(x=>x.value),requestId:crypto.randomUUID()});});
document.addEventListener('change',async e=>{if(e.target.id!=='import-file'||!e.target.files[0])return;try{const text=await e.target.files[0].text();const entries=text.trim().startsWith('[')?JSON.parse(text):text.trim().split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x));await perform(entries[0]?.role?'import-events':'import',{entries});}catch(err){$('notice').textContent=err.message;}});
refresh().catch(e=>$('notice').textContent=e.message);
setInterval(()=>{if(!busy&&tab!=='chat'&&!$('detail').open)refresh().catch(()=>{});},3000);
